{
  "sender_id": "669cf2b9-d06e-4201-ba97-fd9dde1a0418:640ae19e-4fa0-4b1f-b34e-e912776042ec:78b7101d-3d47-4f04-b2e5-a4e672393e42",
  "send_metrics": true,
  "send_errors": true,
  "disable_logging": false
}